services:
  db:
    image: mysql:8.4
    container_name: container_forum_hub

    environment:
      MYSQL_DATABASE: 'db_forum_hub'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'


    ports:
      - '3306:3306'

